name: Deploy the main branch
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd backend/functions && npm ci && npm run build
    - uses: jsryudev/deploy-firebase-functions@v18.0.1
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: cafe-pos-gough
        FUNCTIONS_DIR: backend/functions
